config/routes.rb
Rails.application.routes.draw do
  root 'classrooms#index'
  resources :students, :path => 'estudantes'
  resources :courses, :path => 'cursos'
  resources :classrooms, :path => 'matricula'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  validates :student_id, presence: true
  validates :course_id, presence: true
  validates :entry_at, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :classrooms
	validates :name, presence: true, length: { maximum: 45 }
	validates :description, presence: true, length: { maximum: 45 }
	validates :status, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classrooms
	validates :name, presence: true, length: { maximum: 45 }
	validates :register_number, presence: true, length: { maximum: 45 }
	validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  def index
  	@students_count = Student.count
    @courses_count = Course.count
    @classrooms = Classroom.all
  end

  def show
  end

  def new
    @classroom = Classroom.new
  end

  def edit
  end

  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.entry_at = Time.now
    if @classroom.save
      redirect_to classrooms_path, notice: 'classroom was successfully created.'
    else
      render :new
    end
  end

  def update
    if @classroom.update(classroom_params)
      redirect_to @classroom, notice: 'classroom was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @classroom.destroy
    redirect_to classrooms_path, notice: 'classroom was successfully destroyd.'
  end

  private
  def set_classroom
    @classroom = Classroom.find(params[:id])
  end

  def classroom_params
    params.require(:classroom).permit(
      :student_id,
      :course_id)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
      @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path, notice: 'course was successfully created.'
    else
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'course was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path, notice: 'course was successfully destroyd.'
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(
      :name,
      :description,
      :status)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
      @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: 'student was successfully created.'
    else
      render :new
    end
  end

  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path, notice: 'student was successfully destroyd.'
  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(
      :name,
      :register_number,
      :status)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.erb
<%= simple_form_for @classroom do |f| %>
  <div class="form-group">
    <label>Estudante</label>
    <%= f.input :student_id,:collection => Student.order(:name), label: false, input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label>Curso</label>
    <%= f.input :course_id,:collection => Course.order(:name), label: false, input_html: {class: "form-control"} %>
  </div>
	<%= f.submit "Salvar", class: "btn btn-primary btn-block" %>
<% end %>

app/views/classrooms/_list_enrolment.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Aluno</th>
			<th>Curso</th>
			<th>Data da matrícula</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @classrooms.each do |classroom| %>
		<tr>
			<td><%= classroom.student.name %></td>
			<td><%= classroom.course.name %></td>
			<td><%= classroom.entry_at.strftime("%d-%m-%Y %H:%M") %></td>
			<td><%= link_to "Detalhes", classroom %></td>
			<td><%= link_to "Editar", edit_classroom_path(classroom) %></td>
			<td><%= link_to "Deletar", classroom, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/classrooms/edit.html.erb
<h1>Editar</h1>
<%= render "form" %>

app/views/classrooms/index.html.erb
<h1>Lista de Matrículas</h1>
<% if (@students_count > 0 && @courses_count > 0)%>
	<%= link_to "Nova Matrícula", new_classroom_path, class: "btn btn-success" %>
	<%= render 'list_enrolment' %>
<% else %>
<div class="jumbotron">
	<h2>Você não precisa cadastrar pelo menos um estudante e um curso!</h2>
</div>
<% end %>

app/views/classrooms/new.html.erb
<h1>Novo</h1>
<%= render "form" %>

app/views/classrooms/show.html.erb
<h1>Detalhes</h1>
<p><b>Aluno: </b><%= @classroom.student.register_number %> - <%= @classroom.student.name %></p>
<p><b>Turma: </b><%= @classroom.course.name %></p>
<p><b>Data e Hora da matrícula: </b><%= @classroom.entry_at.strftime("%d-%m-%Y %H:%M") %></p>

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>
  <div class="form-group">
    <label>Nome</label>
    <%= f.input :name, label: false, input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label>Descrição</label>
    <%= f.input :description, label: false, input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label>Status</label>
    <%= f.input :status, label: false, input_html: {class: "form-control"} %>
  </div>

	<%= f.submit "Salvar", class: "btn btn-primary btn-block" %>
<% end %>

app/views/courses/index.html.erb
<h1>Lista de Cursos</h1>
<%= link_to "Novo Curso", new_course_path, class: "btn btn-success" %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Descrição</th>
			<th>Status</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @courses.each do |course| %>
		<tr>
			<td><%= course.name %></td>
			<td><%= course.description %></td>
			<td><%= course.status %></td>
			<td><%= link_to "Detalhes", course %></td>
			<td><%= link_to "Editar", edit_course_path(course) %></td>
			<td><%= link_to "Deletar", course, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/courses/show.html.erb
<h1>Detalhes</h1>
<p><b>Aluno: </b><%= @course.name %></p>
<p><b>Descrição: </b><%= @course.description %></p>
<p><b>Status: </b><%= @course.status %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<div class="masthead">
	<h3 class="text-muted"></h3>
        <nav>
          <ul class="nav nav-justified">
            <li><%= link_to "Matrícula", classrooms_path %></a></li>
            <li><a href="/estudantes">Estudantes</a></li>
            <li><a href="/cursos">Cursos</a></li>
          </ul>
        </nav>
    </div>
<%= yield %>
</div>

</body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for @student do |f| %>
  <div class="form-group">
    <label>Nome</label>
    <%= f.input :name, label: false, input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label>Número de Registro</label>
    <%= f.input :register_number, label: false, input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label>Status</label>
    <%= f.input :status, label: false, input_html: {class: "form-control"} %>
  </div>

	<%= f.submit "Salvar", class: "btn btn-primary btn-block" %>
<% end %>

app/views/students/index.html.erb
<h1>Lista de Estudantes</h1>
<%= link_to "Novo Estudante", new_student_path, class: "btn btn-success" %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Número de Registro</th>
			<th>Status</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @students.each do |student| %>
		<tr>
			<td><%= student.name %></td>
			<td><%= student.register_number %></td>
			<td><%= student.status %></td>
			<td><%= link_to "Detalhes", student %></td>
			<td><%= link_to "Editar", edit_student_path(student) %></td>
			<td><%= link_to "Deletar", student, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/students/show.html.erb
<h1>Detalhes</h1>
<p><b>Aluno: </b><%= @student.name %></p>
<p><b>Número de Registro: </b><%= @student.register_number %></p>
<p><b>Status: </b><%= @student.status %></p>